### ISSUE TITLE
Epic: Migrate from Gatsby to Astro

### ISSUE THREAD

**Issue by WhiteHoodHacker** [sigpwny/websites#190]
Astro has extremely good MDX support and is just well suited for static sites overall. I have already ported over a good chunk of functionality from the current site. Definitely is a much nicer development experience compared to Gatsby.

## Migrated Functionality
- [x] Meetings
  - [x] GFM
  - [x] Katex
- [ ] Events
- [x] Publications
- [x] Profiles
- [x] Markdown pages
- [x] Meeting-Profile relations
- [x] iCalendar generation
- [x] Redirects
- [x] Client-side routing
- [x] Image optimization
- [x] SEO
- [x] Styling
- [x] Popovers
- [ ] Tooltips
- [x] 404 page
- [x] Home page
- [x] Join page
- [x] Migrate existing content
  - [x] Meetings
  - [x] Events
  - [x] Publications
  - [x] Profiles
    - [x] Admins
    - [x] Helpers
    - [x] Alumni
    - [x] Organizations
  - [x] Redirects
- [ ] Updated CMS

## Fixes
- [ ] #4
- [ ] Begins work for #36
- [ ] #98
- [ ] #121
- [x] #140
- [ ] #161
- [x] #176
- [ ] #181
- [x] #186
- [x] #187
- [x] #188

## Known Issues
- ~~It is not possible to use a custom key for references between two content types (e.g. you cannot specify an author's name on a meeting `Minh Duong`, you must use Astro's path ID system `member/minh-duong`)~~
  - ~~**Workaround**: adopt Astro's path ID system. Impact: This adds more friction when creating meetings, but could be improved with a custom CMS widget. This also prevents the easy adding of guest speakers, meaning they need to have a profile created in order for the site to build/pass Zod schema.~~
  - Solved by manually querying profiles and filtering by name.
- ~~It is not possible to co-locate PDFs and other assets with content markdown files.~~
  - ~~**Workaround**: store these assets in `public`. Impact: This adds more friction when creating meetings, but can be improved using CMS custom assets directory upload.~~
  - Solved by using `vite-plugin-static-copy` to copy the entire meetings directory (including assets) into `dist`.
- Plain markdown files (`.md`) will not apply custom component replacements (e.g. to use optimized image components or custom table elements). Previously, this was solved by forcing Gatsby to treat all `.md` files as `.mdx` files, but this does not seem to be configurable within Astro.
  - **Workaround**: Only use `.mdx` files. Impact: minimal.
