### ISSUE TITLE
Epic: Meeting and event publishing workflow

### ISSUE THREAD

**Issue by WhiteHoodHacker** [sigpwny/websites#35]
It would be nice to streamline our entire meeting publication workflow:
- [x] #129
- We have some GitHub Action or webhook workflow that will do the following:
  - [x] Immediately: A calendar event is created to be published to a public Google Calendar, which members can subscribe to (#128)
  - [x] Immediately: A Discord event is created on the server through pwnybot
  - [x] (For the above immediate actions, checks should be performed to ensure that we do not duplicate events if there are updates to the meeting or multiple pushes)
  - [ ] pwnybot or a Discord webhook sends the link to the meeting in #meetings. This could happen automatically 15 minutes before the meeting or at time of meeting. This can also be dynamic based on when slides/videos are uploaded. Or as mentioned below, it can be manually triggered via the `featured` field or equivalent. (#130)

**Comment by reteps** [comment]
Probably wait for #52 to do this

**Comment by WhiteHoodHacker** [comment]
I wasn't planning on it, no. I was thinking that for any upcoming meetings or competitions that we're participating in, we would render that information in our own way. We can add a calendar if we want, but I refuse to display the calendar in Google embed form because it's so ugly 😭.

**Comment by WhiteHoodHacker** [comment]
More notes (from May 29th, 2023): 
![image](https://github.com/sigpwny/sigpwny.com/assets/35712968/a19fa89c-c7b0-4b97-b530-04527df8b971)

Currently, we don't have a solution for Google Calendar or Discord Guild Scheduled Events integrations. For Google Calendar, it could be possible to create a Pipedream workflow that triggers via a GitHub commit with a new/modified event. For Discord, we would need to implement this functionality into pwnybot.

**Comment by WhiteHoodHacker** [comment]
On second thought, this is a horrible way to implement this.

The actual best practice would be to generate an iCalendar (.ics) file and make it available at an endpoint. Then we create a Google Calendar which subscribed to that iCalendar.

It also doesn't look like Google Calendar is able to sync iCalendars immediately (supposedly every 8 hours), so we can combine it with this Google Apps Script to trigger a sync after the site builds: https://github.com/derekantrican/GAS-ICS-Sync

We can also split calendars by year to allow more flexibility.
